/* tslint:disable */
/* eslint-disable */
/**
 * PrintHelm API
 * PrintHelm API OpenAPI Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiAddPrinterConnectionRequest
 */
export interface ApiAddPrinterConnectionRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiAddPrinterConnectionRequest
     */
    'printerId': number;
    /**
     * 
     * @type {string}
     * @memberof ApiAddPrinterConnectionRequest
     */
    'connectionType': ApiAddPrinterConnectionRequestConnectionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiAddPrinterConnectionRequest
     */
    'details'?: string;
}

export const ApiAddPrinterConnectionRequestConnectionTypeEnum = {
    Usb: 'USB',
    Network: 'NETWORK',
    Serial: 'SERIAL',
    Bluetooth: 'BLUETOOTH'
} as const;

export type ApiAddPrinterConnectionRequestConnectionTypeEnum = typeof ApiAddPrinterConnectionRequestConnectionTypeEnum[keyof typeof ApiAddPrinterConnectionRequestConnectionTypeEnum];

/**
 * 
 * @export
 * @interface ApiAdminResetPasswordRequest
 */
export interface ApiAdminResetPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiAdminResetPasswordRequest
     */
    'newPassword': string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiAdminResetPasswordRequest
     */
    'mustChangePassword'?: boolean;
}
/**
 * 
 * @export
 * @interface ApiAuthResponse
 */
export interface ApiAuthResponse {
    /**
     * 
     * @type {ApiUserResponse}
     * @memberof ApiAuthResponse
     */
    'user'?: ApiUserResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthResponse
     */
    'accessToken'?: string;
}
/**
 * 
 * @export
 * @interface ApiChangePasswordRequest
 */
export interface ApiChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiChangePasswordRequest
     */
    'currentPassword': string;
    /**
     * 
     * @type {string}
     * @memberof ApiChangePasswordRequest
     */
    'newPassword': string;
}
/**
 * 
 * @export
 * @interface ApiConnectionConfig
 */
export interface ApiConnectionConfig {
    /**
     * 
     * @type {ConnectionType}
     * @memberof ApiConnectionConfig
     */
    'connectionType': ConnectionType;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'brokerUrl': string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'topic': string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'password'?: string;
}


/**
 * 
 * @export
 * @interface ApiCreatePrinterRequest
 */
export interface ApiCreatePrinterRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'printerName': string;
    /**
     * 
     * @type {PrinterType}
     * @memberof ApiCreatePrinterRequest
     */
    'printerType'?: PrinterType;
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'printerModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {ApiConnectionConfig}
     * @memberof ApiCreatePrinterRequest
     */
    'connectionConfig': ApiConnectionConfig;
}


/**
 * 
 * @export
 * @interface ApiCreateUserRequest
 */
export interface ApiCreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {Array<ApiRole>}
     * @memberof ApiCreateUserRequest
     */
    'roles'?: Array<ApiRole>;
}
/**
 * 
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof ApiErrorResponse
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'error': string;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'path': string;
}
/**
 * 
 * @export
 * @interface ApiFan
 */
export interface ApiFan {
    /**
     * 
     * @type {string}
     * @memberof ApiFan
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiFan
     */
    'speed'?: string;
}
/**
 * 
 * @export
 * @interface ApiIpcam
 */
export interface ApiIpcam {
    /**
     * 
     * @type {string}
     * @memberof ApiIpcam
     */
    'resolution'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiIpcam
     */
    'rtspUrl'?: string;
    /**
     * Timelapse recording mode (e.g. \"timelapse_off\")
     * @type {string}
     * @memberof ApiIpcam
     */
    'timelapse'?: string;
    /**
     * Camera recording state
     * @type {string}
     * @memberof ApiIpcam
     */
    'ipcamRecord'?: string;
    /**
     * Camera device identifier
     * @type {string}
     * @memberof ApiIpcam
     */
    'ipcamDev'?: string;
}
/**
 * 
 * @export
 * @interface ApiLight
 */
export interface ApiLight {
    /**
     * 
     * @type {string}
     * @memberof ApiLight
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLight
     */
    'state'?: string;
}
/**
 * 
 * @export
 * @interface ApiLoginRequest
 */
export interface ApiLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiLoginRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ApiLoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ApiMaterial
 */
export interface ApiMaterial {
    /**
     * 
     * @type {boolean}
     * @memberof ApiMaterial
     */
    'loaded'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMaterial
     */
    'totalWeightGrams'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMaterial
     */
    'costPerGram'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'timestamp'?: string;
    /**
     * Estimated filament remaining (%)
     * @type {number}
     * @memberof ApiMaterial
     */
    'remain'?: number;
    /**
     * Filament diameter (e.g. \"1.75\")
     * @type {string}
     * @memberof ApiMaterial
     */
    'trayDiameter'?: string;
    /**
     * Spool weight in grams as reported by AMS tag
     * @type {string}
     * @memberof ApiMaterial
     */
    'trayWeight'?: string;
    /**
     * RFID UUID of the tray tag
     * @type {string}
     * @memberof ApiMaterial
     */
    'trayUuid'?: string;
    /**
     * Minimum recommended nozzle temperature for this filament
     * @type {string}
     * @memberof ApiMaterial
     */
    'nozzleTempMin'?: string;
    /**
     * Maximum recommended nozzle temperature for this filament
     * @type {string}
     * @memberof ApiMaterial
     */
    'nozzleTempMax'?: string;
    /**
     * Recommended bed temperature for this filament
     * @type {string}
     * @memberof ApiMaterial
     */
    'recommendedBedTemp'?: string;
    /**
     * Recommended drying temperature
     * @type {string}
     * @memberof ApiMaterial
     */
    'dryingTemp'?: string;
    /**
     * Recommended drying time in hours
     * @type {string}
     * @memberof ApiMaterial
     */
    'dryingTime'?: string;
}
/**
 * 
 * @export
 * @interface ApiMaterialSystem
 */
export interface ApiMaterialSystem {
    /**
     * 
     * @type {string}
     * @memberof ApiMaterialSystem
     */
    'humidity'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterialSystem
     */
    'temperature'?: string;
    /**
     * 
     * @type {Array<ApiMaterial>}
     * @memberof ApiMaterialSystem
     */
    'materials'?: Array<ApiMaterial>;
}
/**
 * 
 * @export
 * @interface ApiMqttConnectionConfig
 */
export interface ApiMqttConnectionConfig {
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'brokerUrl': string;
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'topic': string;
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'password'?: string;
}
/**
 * 
 * @export
 * @interface ApiPrinterResponse
 */
export interface ApiPrinterResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterResponse
     */
    'printerId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterResponse
     */
    'printerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterResponse
     */
    'printerModel'?: string;
    /**
     * 
     * @type {PrinterType}
     * @memberof ApiPrinterResponse
     */
    'printerType'?: PrinterType;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterResponse
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterResponse
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {ApiConnectionConfig}
     * @memberof ApiPrinterResponse
     */
    'connectionConfig'?: ApiConnectionConfig;
}


/**
 * 
 * @export
 * @interface ApiPrinterState
 */
export interface ApiPrinterState {
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'printerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'currentLayer'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'totalLayers'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'state'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'bedTemp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'bedTargetTemp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'nozzleTargetTemp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'nozzleDiameter'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'subtask'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'nozzleTemp'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'ipAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'file'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'timestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'progress'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'wifiSignalStrength'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'subtaskName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'subtaskId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'nozzleType'?: string;
    /**
     * Estimated remaining print time in minutes
     * @type {number}
     * @memberof ApiPrinterState
     */
    'remainTime'?: number;
    /**
     * Raw gcode execution state reported by the printer
     * @type {string}
     * @memberof ApiPrinterState
     */
    'gcodeState'?: string;
    /**
     * Type of print job (local, cloud, etc.)
     * @type {string}
     * @memberof ApiPrinterState
     */
    'printType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'taskId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'jobId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'projectId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'profileId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'modelId'?: string;
    /**
     * Whether an SD card is inserted
     * @type {boolean}
     * @memberof ApiPrinterState
     */
    'sdcard'?: boolean;
    /**
     * Bitmask of homed axes reported by the printer
     * @type {number}
     * @memberof ApiPrinterState
     */
    'homeFlag'?: number;
    /**
     * Speed level preset (1=silent, 2=standard, 3=sport, 4=ludicrous)
     * @type {number}
     * @memberof ApiPrinterState
     */
    'spdLvl'?: number;
    /**
     * Speed magnitude as a percentage
     * @type {number}
     * @memberof ApiPrinterState
     */
    'spdMag'?: number;
    /**
     * Print error code (0 = no error)
     * @type {number}
     * @memberof ApiPrinterState
     */
    'printError'?: number;
    /**
     * Motion controller print error code
     * @type {string}
     * @memberof ApiPrinterState
     */
    'mcPrintErrorCode'?: string;
    /**
     * Human-readable failure reason if print failed
     * @type {string}
     * @memberof ApiPrinterState
     */
    'failReason'?: string;
    /**
     * 
     * @type {ApiMaterialSystem}
     * @memberof ApiPrinterState
     */
    'materialSystem'?: ApiMaterialSystem;
    /**
     * 
     * @type {Array<ApiFan>}
     * @memberof ApiPrinterState
     */
    'fans'?: Array<ApiFan>;
    /**
     * 
     * @type {Array<ApiLight>}
     * @memberof ApiPrinterState
     */
    'lights'?: Array<ApiLight>;
    /**
     * 
     * @type {ApiIpcam}
     * @memberof ApiPrinterState
     */
    'ipcam'?: ApiIpcam;
    /**
     * 
     * @type {ApiXcam}
     * @memberof ApiPrinterState
     */
    'xcam'?: ApiXcam;
    /**
     * 
     * @type {ApiUpgradeState}
     * @memberof ApiPrinterState
     */
    'upgradeState'?: ApiUpgradeState;
}
/**
 * 
 * @export
 * @interface ApiRefreshRequest
 */
export interface ApiRefreshRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiRefreshRequest
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface ApiRole
 */
export interface ApiRole {
    /**
     * 
     * @type {number}
     * @memberof ApiRole
     */
    'roleId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiRole
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiRole
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface ApiUpdatePrinterRequest
 */
export interface ApiUpdatePrinterRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiUpdatePrinterRequest
     */
    'printerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUpdatePrinterRequest
     */
    'printerModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUpdatePrinterRequest
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUpdatePrinterRequest
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {ApiConnectionConfig}
     * @memberof ApiUpdatePrinterRequest
     */
    'connectionConfig'?: ApiConnectionConfig;
}
/**
 * 
 * @export
 * @interface ApiUpdateUserRequest
 */
export interface ApiUpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiUpdateUserRequest
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUpdateUserRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUpdateUserRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiUpdateUserRequest
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Array<ApiRole>}
     * @memberof ApiUpdateUserRequest
     */
    'roles'?: Array<ApiRole>;
}
/**
 * 
 * @export
 * @interface ApiUpgradeState
 */
export interface ApiUpgradeState {
    /**
     * Current upgrade status (e.g. IDLE, DOWNLOADING, INSTALLING)
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'status'?: string;
    /**
     * Upgrade progress percentage as a string
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'progress'?: string;
    /**
     * Available OTA firmware version
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'otaNewVersionNumber'?: string;
    /**
     * Available AMS firmware version
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'amsNewVersionNumber'?: string;
    /**
     * Available AHB firmware version
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'ahbNewVersionNumber'?: string;
    /**
     * Available extruder firmware version
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'extNewVersionNumber'?: string;
    /**
     * Human-readable status message
     * @type {string}
     * @memberof ApiUpgradeState
     */
    'message'?: string;
    /**
     * Whether this upgrade is mandatory
     * @type {boolean}
     * @memberof ApiUpgradeState
     */
    'forceUpgrade'?: boolean;
}
/**
 * 
 * @export
 * @interface ApiUserResponse
 */
export interface ApiUserResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiUserResponse
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserResponse
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUserResponse
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiUserResponse
     */
    'lastName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiUserResponse
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiUserResponse
     */
    'mustChangePassword'?: boolean;
    /**
     * 
     * @type {Array<ApiRole>}
     * @memberof ApiUserResponse
     */
    'roles'?: Array<ApiRole>;
}
/**
 * AI-based visual monitoring settings (X1 series)
 * @export
 * @interface ApiXcam
 */
export interface ApiXcam {
    /**
     * First layer inspection enabled
     * @type {boolean}
     * @memberof ApiXcam
     */
    'firstLayerInspector'?: boolean;
    /**
     * Build plate marker detection enabled
     * @type {boolean}
     * @memberof ApiXcam
     */
    'buildplateMarkerDetector'?: boolean;
    /**
     * Spaghetti failure detection enabled
     * @type {boolean}
     * @memberof ApiXcam
     */
    'spaghettiDetector'?: boolean;
    /**
     * General printing monitor enabled
     * @type {boolean}
     * @memberof ApiXcam
     */
    'printingMonitor'?: boolean;
    /**
     * Whether the printer will halt on a detected failure
     * @type {boolean}
     * @memberof ApiXcam
     */
    'printHalt'?: boolean;
    /**
     * Sensitivity level for halt-on-failure (low / medium / high)
     * @type {string}
     * @memberof ApiXcam
     */
    'haltPrintSensitivity'?: string;
    /**
     * Allow skipping failed objects
     * @type {boolean}
     * @memberof ApiXcam
     */
    'allowSkipParts'?: boolean;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const ConnectionType = {
    Usb: 'USB',
    Network: 'NETWORK',
    Serial: 'SERIAL',
    Bluetooth: 'BLUETOOTH',
    Mqtt: 'MQTT'
} as const;

export type ConnectionType = typeof ConnectionType[keyof typeof ConnectionType];


/**
 * 
 * @export
 * @interface CreatePrinter201Response
 */
export interface CreatePrinter201Response {
    /**
     * 
     * @type {number}
     * @memberof CreatePrinter201Response
     */
    'printerId'?: number;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const PrinterType = {
    Bambulab: 'BAMBULAB',
    Prusa: 'PRUSA',
    Anycubic: 'ANYCUBIC',
    Epax: 'EPAX',
    Elegoo: 'ELEGOO',
    Other: 'OTHER'
} as const;

export type PrinterType = typeof PrinterType[keyof typeof PrinterType];



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary User login
         * @param {ApiLoginRequest} apiLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (apiLoginRequest: ApiLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiLoginRequest' is not null or undefined
            assertParamExists('login', 'apiLoginRequest', apiLoginRequest)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refresh: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary User login
         * @param {ApiLoginRequest} apiLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(apiLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refresh(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refresh(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.refresh']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary User login
         * @param {ApiLoginRequest} apiLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthResponse> {
            return localVarFp.login(apiLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary User logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refresh(options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthResponse> {
            return localVarFp.refresh(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary User login
     * @param {ApiLoginRequest} apiLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(apiLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary User logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public logout(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public refresh(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).refresh(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PrinterApi - axios parameter creator
 * @export
 */
export const PrinterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new printer
         * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPrinter: async (apiCreatePrinterRequest: ApiCreatePrinterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiCreatePrinterRequest' is not null or undefined
            assertParamExists('createPrinter', 'apiCreatePrinterRequest', apiCreatePrinterRequest)
            const localVarPath = `/printer/createPrinter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiCreatePrinterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a printer
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrinter: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePrinter', 'id', id)
            const localVarPath = `/printer/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a printer by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrinterById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPrinterById', 'id', id)
            const localVarPath = `/printer/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all printers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrinters: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/printer`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a printer
         * @param {number} id 
         * @param {ApiUpdatePrinterRequest} apiUpdatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePrinter: async (id: number, apiUpdatePrinterRequest: ApiUpdatePrinterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePrinter', 'id', id)
            // verify required parameter 'apiUpdatePrinterRequest' is not null or undefined
            assertParamExists('updatePrinter', 'apiUpdatePrinterRequest', apiUpdatePrinterRequest)
            const localVarPath = `/printer/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiUpdatePrinterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PrinterApi - functional programming interface
 * @export
 */
export const PrinterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PrinterApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new printer
         * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrinter201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPrinter(apiCreatePrinterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrinterApi.createPrinter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a printer
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePrinter(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePrinter(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrinterApi.deletePrinter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a printer by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPrinterById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiPrinterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPrinterById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrinterApi.getPrinterById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all printers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPrinters(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApiPrinterResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPrinters(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrinterApi.getPrinters']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a printer
         * @param {number} id 
         * @param {ApiUpdatePrinterRequest} apiUpdatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePrinter(id: number, apiUpdatePrinterRequest: ApiUpdatePrinterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiPrinterResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePrinter(id, apiUpdatePrinterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrinterApi.updatePrinter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PrinterApi - factory interface
 * @export
 */
export const PrinterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PrinterApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new printer
         * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrinter201Response> {
            return localVarFp.createPrinter(apiCreatePrinterRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a printer
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePrinter(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePrinter(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a printer by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrinterById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiPrinterResponse> {
            return localVarFp.getPrinterById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all printers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPrinters(options?: RawAxiosRequestConfig): AxiosPromise<Array<ApiPrinterResponse>> {
            return localVarFp.getPrinters(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a printer
         * @param {number} id 
         * @param {ApiUpdatePrinterRequest} apiUpdatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePrinter(id: number, apiUpdatePrinterRequest: ApiUpdatePrinterRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiPrinterResponse> {
            return localVarFp.updatePrinter(id, apiUpdatePrinterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PrinterApi - object-oriented interface
 * @export
 * @class PrinterApi
 * @extends {BaseAPI}
 */
export class PrinterApi extends BaseAPI {
    /**
     * 
     * @summary Create a new printer
     * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApi
     */
    public createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig) {
        return PrinterApiFp(this.configuration).createPrinter(apiCreatePrinterRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a printer
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApi
     */
    public deletePrinter(id: number, options?: RawAxiosRequestConfig) {
        return PrinterApiFp(this.configuration).deletePrinter(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a printer by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApi
     */
    public getPrinterById(id: number, options?: RawAxiosRequestConfig) {
        return PrinterApiFp(this.configuration).getPrinterById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all printers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApi
     */
    public getPrinters(options?: RawAxiosRequestConfig) {
        return PrinterApiFp(this.configuration).getPrinters(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a printer
     * @param {number} id 
     * @param {ApiUpdatePrinterRequest} apiUpdatePrinterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApi
     */
    public updatePrinter(id: number, apiUpdatePrinterRequest: ApiUpdatePrinterRequest, options?: RawAxiosRequestConfig) {
        return PrinterApiFp(this.configuration).updatePrinter(id, apiUpdatePrinterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RoleApi - axios parameter creator
 * @export
 */
export const RoleApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get all roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoles: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/role`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoleApi - functional programming interface
 * @export
 */
export const RoleApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoleApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get all roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoles(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApiRole>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoles(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoleApi.getRoles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoleApi - factory interface
 * @export
 */
export const RoleApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoleApiFp(configuration)
    return {
        /**
         * 
         * @summary Get all roles
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoles(options?: RawAxiosRequestConfig): AxiosPromise<Array<ApiRole>> {
            return localVarFp.getRoles(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoleApi - object-oriented interface
 * @export
 * @class RoleApi
 * @extends {BaseAPI}
 */
export class RoleApi extends BaseAPI {
    /**
     * 
     * @summary Get all roles
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleApi
     */
    public getRoles(options?: RawAxiosRequestConfig) {
        return RoleApiFp(this.configuration).getRoles(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Admin reset user password
         * @param {number} id 
         * @param {ApiAdminResetPasswordRequest} apiAdminResetPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminResetPassword: async (id: number, apiAdminResetPasswordRequest: ApiAdminResetPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('adminResetPassword', 'id', id)
            // verify required parameter 'apiAdminResetPasswordRequest' is not null or undefined
            assertParamExists('adminResetPassword', 'apiAdminResetPasswordRequest', apiAdminResetPasswordRequest)
            const localVarPath = `/user/{id}/password`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiAdminResetPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Change own password
         * @param {ApiChangePasswordRequest} apiChangePasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeMyPassword: async (apiChangePasswordRequest: ApiChangePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiChangePasswordRequest' is not null or undefined
            assertParamExists('changeMyPassword', 'apiChangePasswordRequest', apiChangePasswordRequest)
            const localVarPath = `/user/me/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiChangePasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new user
         * @param {ApiCreateUserRequest} apiCreateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (apiCreateUserRequest: ApiCreateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiCreateUserRequest' is not null or undefined
            assertParamExists('createUser', 'apiCreateUserRequest', apiCreateUserRequest)
            const localVarPath = `/user/createUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiCreateUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a user
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUser', 'id', id)
            const localVarPath = `/user/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getUserById', 'id', id)
            const localVarPath = `/user/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user
         * @param {number} id 
         * @param {ApiUpdateUserRequest} apiUpdateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser: async (id: number, apiUpdateUserRequest: ApiUpdateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateUser', 'id', id)
            // verify required parameter 'apiUpdateUserRequest' is not null or undefined
            assertParamExists('updateUser', 'apiUpdateUserRequest', apiUpdateUserRequest)
            const localVarPath = `/user/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiUpdateUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Admin reset user password
         * @param {number} id 
         * @param {ApiAdminResetPasswordRequest} apiAdminResetPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminResetPassword(id: number, apiAdminResetPasswordRequest: ApiAdminResetPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adminResetPassword(id, apiAdminResetPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.adminResetPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Change own password
         * @param {ApiChangePasswordRequest} apiChangePasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeMyPassword(apiChangePasswordRequest: ApiChangePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeMyPassword(apiChangePasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.changeMyPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new user
         * @param {ApiCreateUserRequest} apiCreateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(apiCreateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a user
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.deleteUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get current authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUsers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApiUserResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUsers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user
         * @param {number} id 
         * @param {ApiUpdateUserRequest} apiUpdateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser(id: number, apiUpdateUserRequest: ApiUpdateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(id, apiUpdateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.updateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Admin reset user password
         * @param {number} id 
         * @param {ApiAdminResetPasswordRequest} apiAdminResetPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminResetPassword(id: number, apiAdminResetPasswordRequest: ApiAdminResetPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.adminResetPassword(id, apiAdminResetPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Change own password
         * @param {ApiChangePasswordRequest} apiChangePasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeMyPassword(apiChangePasswordRequest: ApiChangePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.changeMyPassword(apiChangePasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new user
         * @param {ApiCreateUserRequest} apiCreateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiUserResponse> {
            return localVarFp.createUser(apiCreateUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a user
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(id: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<ApiUserResponse> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ApiUserResponse> {
            return localVarFp.getUserById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUsers(options?: RawAxiosRequestConfig): AxiosPromise<Array<ApiUserResponse>> {
            return localVarFp.getUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user
         * @param {number} id 
         * @param {ApiUpdateUserRequest} apiUpdateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser(id: number, apiUpdateUserRequest: ApiUpdateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiUserResponse> {
            return localVarFp.updateUser(id, apiUpdateUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Admin reset user password
     * @param {number} id 
     * @param {ApiAdminResetPasswordRequest} apiAdminResetPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public adminResetPassword(id: number, apiAdminResetPasswordRequest: ApiAdminResetPasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).adminResetPassword(id, apiAdminResetPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Change own password
     * @param {ApiChangePasswordRequest} apiChangePasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public changeMyPassword(apiChangePasswordRequest: ApiChangePasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).changeMyPassword(apiChangePasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new user
     * @param {ApiCreateUserRequest} apiCreateUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).createUser(apiCreateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a user
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public deleteUser(id: number, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).deleteUser(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get current authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user by ID
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserById(id: number, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUsers(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user
     * @param {number} id 
     * @param {ApiUpdateUserRequest} apiUpdateUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public updateUser(id: number, apiUpdateUserRequest: ApiUpdateUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).updateUser(id, apiUpdateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



