/* tslint:disable */
/* eslint-disable */
/**
 * PrintHelm API
 * PrintHelm API OpenAPI Specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ApiAddPrinterConnectionRequest
 */
export interface ApiAddPrinterConnectionRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiAddPrinterConnectionRequest
     */
    'printerId': number;
    /**
     * 
     * @type {string}
     * @memberof ApiAddPrinterConnectionRequest
     */
    'connectionType': ApiAddPrinterConnectionRequestConnectionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ApiAddPrinterConnectionRequest
     */
    'details'?: string;
}

export const ApiAddPrinterConnectionRequestConnectionTypeEnum = {
    Usb: 'USB',
    Network: 'NETWORK',
    Serial: 'SERIAL',
    Bluetooth: 'BLUETOOTH'
} as const;

export type ApiAddPrinterConnectionRequestConnectionTypeEnum = typeof ApiAddPrinterConnectionRequestConnectionTypeEnum[keyof typeof ApiAddPrinterConnectionRequestConnectionTypeEnum];

/**
 * 
 * @export
 * @interface ApiAuthResponse
 */
export interface ApiAuthResponse {
    /**
     * 
     * @type {ApiUserResponse}
     * @memberof ApiAuthResponse
     */
    'user'?: ApiUserResponse;
    /**
     * 
     * @type {string}
     * @memberof ApiAuthResponse
     */
    'accessToken'?: string;
}
/**
 * 
 * @export
 * @interface ApiConnectionConfig
 */
export interface ApiConnectionConfig {
    /**
     * 
     * @type {ConnectionType}
     * @memberof ApiConnectionConfig
     */
    'connectionType': ConnectionType;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'brokerUrl': string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'topic': string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionConfig
     */
    'password'?: string;
}


/**
 * 
 * @export
 * @interface ApiCreatePrinterRequest
 */
export interface ApiCreatePrinterRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'printerName': string;
    /**
     * 
     * @type {PrinterType}
     * @memberof ApiCreatePrinterRequest
     */
    'printerType'?: PrinterType;
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'printerModel'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreatePrinterRequest
     */
    'serialNumber'?: string;
    /**
     * 
     * @type {ApiConnectionConfig}
     * @memberof ApiCreatePrinterRequest
     */
    'connectionConfig': ApiConnectionConfig;
}


/**
 * 
 * @export
 * @interface ApiCreateUserRequest
 */
export interface ApiCreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCreateUserRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {Array<ApiRole>}
     * @memberof ApiCreateUserRequest
     */
    'roles'?: Array<ApiRole>;
}
/**
 * 
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'timestamp': string;
    /**
     * 
     * @type {number}
     * @memberof ApiErrorResponse
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'error': string;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'message': string;
    /**
     * 
     * @type {string}
     * @memberof ApiErrorResponse
     */
    'path': string;
}
/**
 * 
 * @export
 * @interface ApiFan
 */
export interface ApiFan {
    /**
     * 
     * @type {string}
     * @memberof ApiFan
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiFan
     */
    'speed'?: string;
}
/**
 * 
 * @export
 * @interface ApiLight
 */
export interface ApiLight {
    /**
     * 
     * @type {string}
     * @memberof ApiLight
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiLight
     */
    'state'?: string;
}
/**
 * 
 * @export
 * @interface ApiLoginRequest
 */
export interface ApiLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiLoginRequest
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof ApiLoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ApiMaterial
 */
export interface ApiMaterial {
    /**
     * 
     * @type {boolean}
     * @memberof ApiMaterial
     */
    'loaded'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'color'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiMaterial
     */
    'totalWeightGrams'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiMaterial
     */
    'costPerGram'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterial
     */
    'timestamp'?: string;
}
/**
 * 
 * @export
 * @interface ApiMaterialSystem
 */
export interface ApiMaterialSystem {
    /**
     * 
     * @type {string}
     * @memberof ApiMaterialSystem
     */
    'humidity'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMaterialSystem
     */
    'temperature'?: string;
    /**
     * 
     * @type {Array<ApiMaterial>}
     * @memberof ApiMaterialSystem
     */
    'materials'?: Array<ApiMaterial>;
}
/**
 * 
 * @export
 * @interface ApiMqttConnectionConfig
 */
export interface ApiMqttConnectionConfig {
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'brokerUrl': string;
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'topic': string;
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiMqttConnectionConfig
     */
    'password'?: string;
}
/**
 * 
 * @export
 * @interface ApiPrinterState
 */
export interface ApiPrinterState {
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'printerId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'currentLayer'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'totalLayers'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'state'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'bedTemp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'bedTargetTemp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'nozzleTargetTemp'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'nozzleDiameter'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'subtask'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'nozzleTemp'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'ipAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'file'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'timestamp'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiPrinterState
     */
    'progress'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'wifiSignalStrength'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'subtaskName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiPrinterState
     */
    'nozzleType'?: string;
    /**
     * 
     * @type {ApiMaterialSystem}
     * @memberof ApiPrinterState
     */
    'materialSystem'?: ApiMaterialSystem;
    /**
     * 
     * @type {Array<ApiFan>}
     * @memberof ApiPrinterState
     */
    'fans'?: Array<ApiFan>;
    /**
     * 
     * @type {Array<ApiLight>}
     * @memberof ApiPrinterState
     */
    'lights'?: Array<ApiLight>;
}
/**
 * 
 * @export
 * @interface ApiRefreshRequest
 */
export interface ApiRefreshRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiRefreshRequest
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface ApiRole
 */
export interface ApiRole {
    /**
     * 
     * @type {number}
     * @memberof ApiRole
     */
    'roleId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiRole
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiRole
     */
    'description'?: string;
}
/**
 * 
 * @export
 * @interface ApiUserResponse
 */
export interface ApiUserResponse {
    /**
     * 
     * @type {number}
     * @memberof ApiUserResponse
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiUserResponse
     */
    'username'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiUserResponse
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {Array<ApiRole>}
     * @memberof ApiUserResponse
     */
    'roles'?: Array<ApiRole>;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const ConnectionType = {
    Usb: 'USB',
    Network: 'NETWORK',
    Serial: 'SERIAL',
    Bluetooth: 'BLUETOOTH',
    Mqtt: 'MQTT'
} as const;

export type ConnectionType = typeof ConnectionType[keyof typeof ConnectionType];


/**
 * 
 * @export
 * @interface CreatePrinter201Response
 */
export interface CreatePrinter201Response {
    /**
     * 
     * @type {number}
     * @memberof CreatePrinter201Response
     */
    'printerId'?: number;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const PrinterType = {
    Bambulab: 'BAMBULAB',
    Prusa: 'PRUSA',
    Anycubic: 'ANYCUBIC',
    Epax: 'EPAX',
    Elegoo: 'ELEGOO',
    Other: 'OTHER'
} as const;

export type PrinterType = typeof PrinterType[keyof typeof PrinterType];



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary User login
         * @param {ApiLoginRequest} apiLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (apiLoginRequest: ApiLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiLoginRequest' is not null or undefined
            assertParamExists('login', 'apiLoginRequest', apiLoginRequest)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refresh: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary User login
         * @param {ApiLoginRequest} apiLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(apiLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async refresh(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAuthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.refresh(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.refresh']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary User login
         * @param {ApiLoginRequest} apiLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthResponse> {
            return localVarFp.login(apiLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        refresh(options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthResponse> {
            return localVarFp.refresh(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - interface
 * @export
 * @interface AuthApi
 */
export interface AuthApiInterface {
    /**
     * 
     * @summary User login
     * @param {ApiLoginRequest} apiLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthResponse>;

    /**
     * 
     * @summary Refresh access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApiInterface
     */
    refresh(options?: RawAxiosRequestConfig): AxiosPromise<ApiAuthResponse>;

}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI implements AuthApiInterface {
    /**
     * 
     * @summary User login
     * @param {ApiLoginRequest} apiLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(apiLoginRequest: ApiLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(apiLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public refresh(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).refresh(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PrinterApi - axios parameter creator
 * @export
 */
export const PrinterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new printer
         * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPrinter: async (apiCreatePrinterRequest: ApiCreatePrinterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiCreatePrinterRequest' is not null or undefined
            assertParamExists('createPrinter', 'apiCreatePrinterRequest', apiCreatePrinterRequest)
            const localVarPath = `/printer/createPrinter`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiCreatePrinterRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PrinterApi - functional programming interface
 * @export
 */
export const PrinterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PrinterApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new printer
         * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreatePrinter201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPrinter(apiCreatePrinterRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PrinterApi.createPrinter']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PrinterApi - factory interface
 * @export
 */
export const PrinterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PrinterApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new printer
         * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrinter201Response> {
            return localVarFp.createPrinter(apiCreatePrinterRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PrinterApi - interface
 * @export
 * @interface PrinterApi
 */
export interface PrinterApiInterface {
    /**
     * 
     * @summary Create a new printer
     * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApiInterface
     */
    createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreatePrinter201Response>;

}

/**
 * PrinterApi - object-oriented interface
 * @export
 * @class PrinterApi
 * @extends {BaseAPI}
 */
export class PrinterApi extends BaseAPI implements PrinterApiInterface {
    /**
     * 
     * @summary Create a new printer
     * @param {ApiCreatePrinterRequest} apiCreatePrinterRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PrinterApi
     */
    public createPrinter(apiCreatePrinterRequest: ApiCreatePrinterRequest, options?: RawAxiosRequestConfig) {
        return PrinterApiFp(this.configuration).createPrinter(apiCreatePrinterRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new user
         * @param {ApiCreateUserRequest} apiCreateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (apiCreateUserRequest: ApiCreateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiCreateUserRequest' is not null or undefined
            assertParamExists('createUser', 'apiCreateUserRequest', apiCreateUserRequest)
            const localVarPath = `/user/createUser`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiCreateUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new user
         * @param {ApiCreateUserRequest} apiCreateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(apiCreateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new user
         * @param {ApiCreateUserRequest} apiCreateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiUserResponse> {
            return localVarFp.createUser(apiCreateUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - interface
 * @export
 * @interface UserApi
 */
export interface UserApiInterface {
    /**
     * 
     * @summary Create a new user
     * @param {ApiCreateUserRequest} apiCreateUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApiInterface
     */
    createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiUserResponse>;

}

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI implements UserApiInterface {
    /**
     * 
     * @summary Create a new user
     * @param {ApiCreateUserRequest} apiCreateUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public createUser(apiCreateUserRequest: ApiCreateUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).createUser(apiCreateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



